[package]
name = "rendering"
version = "0.2.0"
authors = ["Julian T <julian@jtle.dk>"]
readme = "readme.md"
repository = "https://github.com/jbjjbjjbj/rendering"
license = "GPL-3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
rand = "0.8.3"
rand_pcg = "0.3.0"
crossbeam = "0.8.0"
